# Generated by Django 4.2.2 on 2023-08-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_todotask_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='description',
            new_name='desc',
        ),
    ]
