# Generated by Django 4.2.2 on 2023-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_api", "0003_rename_description_todotask_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="todotask",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
